import React from "react";
import { ClientOnly } from "../client/ClientOnly";
import { memoizeOnId } from "../lib/memoizeOnId";
import { getLookupCandidates } from "./lookupCandidates";

let useClientLookupPromise: Promise<Record<string, () => Promise<any>>> | undefined;

const getUseClientLookup = () => {
  useClientLookupPromise ??= import(
    // @ts-expect-error virtual module generated by Redwood's Vite plugins
    "virtual:use-client-lookup.js"
  ).then((module) => module.useClientLookup);

  return useClientLookupPromise;
};

export const loadModule = memoizeOnId(async (id: string) => {
  const useClientLookup = await getUseClientLookup();
  const moduleFn = getLookupCandidates(id)
    .map((candidate) => useClientLookup[candidate])
    .find(Boolean);

  if (!moduleFn) {
    throw new Error(
      `(client) No module found for '${id}' in module lookup for "use client" directive`,
    );
  }

  return await moduleFn();
});

// context(justinvdm, 2 Dec 2024): re memoize(): React relies on the same promise instance being returned for the same id
export const clientWebpackRequire = memoizeOnId(async (id: string) => {
  const [file, name] = id.split("#");
  const promisedModule = loadModule(file);

  if (!name) {
    return await promisedModule;
  }

  const promisedComponent = promisedModule.then((module) => module[name]);

  const didSSR = (globalThis as any).__RWSDK_CONTEXT?.rw?.ssr;

  if (didSSR) {
    const awaitedComponent = await promisedComponent;
    return { [id]: awaitedComponent };
  }
  const promisedDefault = promisedComponent.then((Component) => ({
    default: Component,
  }));

  const Lazy = React.lazy(() => promisedDefault);

  const Wrapped = (props: any) =>
    React.createElement(ClientOnly, null, React.createElement(Lazy, props));

  return { [id]: Wrapped };
});
