// Generated by Wrangler by running `wrangler types`

interface Env {
	APP_NAME: "__change_me__";
	RP_ID: string;
	SECRET_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
	DB: D1Database;
	ASSETS: Fetcher;
}
