// Generated by Wrangler by running `wrangler types`

interface Env {
	SECRET_KEY: string;
	SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
	ASSETS: Fetcher;
}
