name: Code Quality

on:
  push:
    branches:
      - main
    paths:
      - "sdk/**"
      - "starter/**"
      - "addons/**"
      - "community/**"
  pull_request:
    paths:
      - "sdk/**"
      - "starter/**"
      - "addons/**"
      - "community/**"

jobs:
  check-sdk:
    name: Core Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.14.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build SDK
        run: pnpm build
        working-directory: sdk

      - name: Run tests
        run: pnpm test
        working-directory: sdk

      - name: Typecheck Addons
        run: pnpm typecheck:addons

      - name: Typecheck Starter
        run: pnpm typecheck:starter

  check-community:
    name: Community Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.14.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build SDK
        run: pnpm build
        working-directory: sdk

      - name: Build Community
        run: pnpm build
        working-directory: community

      - name: Run tests
        run: pnpm test
        working-directory: community

      - name: Typecheck Community
        run: pnpm typecheck:community
