name: Starter Smoke Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  smoke-test:
    name: ${{ matrix.starter }} starter - ${{ matrix.os }} - ${{ matrix.package-manager }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        starter: [minimal, standard]
        os: [windows-latest] # Focused Windows testing for path fixes
        # os: [ubuntu-latest] # Temporarily disabled for focused Windows testing
        package-manager: [pnpm] # Focused on single package manager for testing
        # package-manager: [pnpm, npm, yarn, yarn-classic] # Temporarily disabled for focused testing

    # context(justinvdm, 2025-05-12):
    # Only run this job for PRs from the same repository and pushes to main
    # For security, GH won't expose secrets for fork PRs
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        shell: bash
        run: |
          corepack enable
          if [ "${{ matrix.package-manager }}" = "yarn" ]; then
            corepack prepare yarn@stable --activate
          elif [ "${{ matrix.package-manager }}" = "yarn-classic" ]; then
            npm i -g yarn@1.22.19 --force
          fi
          pnpm install

      - name: Run smoke test
        shell: bash
        run: |
          ./sdk/scripts/ci-smoke-test.sh --starter "${{ matrix.starter }}" --package-manager "${{ matrix.package-manager }}"
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}

      - name: Upload starter artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-test-artifacts-${{ matrix.starter }}-${{ matrix.os }}-${{ matrix.package-manager }}
          path: smoke-test-artifacts/${{ matrix.starter }}
          retention-days: 7
