name: Starter Smoke Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  smoke-test:
    name: ${{ matrix.starter }} starter - ${{ matrix.os }} - ${{ matrix.package-manager }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        starter: [minimal, standard]
        os: [windows-latest] # Focused Windows testing for path fixes
        # os: [ubuntu-latest] # Temporarily disabled for focused Windows testing
        package-manager: [pnpm] # Focused on single package manager for testing
        # package-manager: [pnpm, npm, yarn, yarn-classic] # Temporarily disabled for focused testing

    # context(justinvdm, 2025-05-12):
    # Only run this job for PRs from the same repository, pushes to main, or manual dispatch
    # For security, GH won't expose secrets for fork PRs
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Clear pnpm cache
        shell: bash
        run: pnpm store prune

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Run isolated directive scan test
        shell: bash
        run: |
          cd starters/minimal
          node ../../sdk/scripts/test-directive-scan.mjs
        env:
          DEBUG: "rwsdk:*"
          CI: 1

      - name: Run smoke test
        if: false # Temporarily disable the full smoke test
        run: pnpm smoke-test --starter ${{ matrix.starter }} --pm ${{ matrix.package-manager }}
        env:
          DEBUG: "rwsdk:*"
          CI: 1
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Run smoke test (yarn classic)
        if: matrix.package-manager == 'yarn-classic'
        run: yarn smoke-test --starter ${{ matrix.starter }} --pm ${{ matrix.package-manager }}
        env:
          DEBUG: "rwsdk:*"
          CI: 1
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          # context(justinvdm, 15 Sep 2025): Yarn classic does not correctly handle the `pre` and `post` lifecycle

      - name: Upload starter artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-test-artifacts-${{ matrix.starter }}-${{ matrix.os }}-${{ matrix.package-manager }}
          path: smoke-test-artifacts/${{ matrix.starter }}
          retention-days: 7
