name: Test Renovate Flow

on:
  workflow_dispatch:
  push:
    branches:
      - greenkeep-now-and-ongoing

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Renovate
        uses: renovatebot/github-action@v40.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json
          renovate-args: --autodiscover=true --autodiscover-filter=${{ github.repository }}
