name: Simple Workflow Test

on:
  workflow_dispatch:
  push:
    branches:
      - greenkeep-now-and-ongoing

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Workflow is running"
